# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-22 08:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0002_auto_20180422_0853'),
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='category_post',
        ),
        migrations.AddField(
            model_name='post',
            name='category_post',
            field=models.ManyToManyField(blank=True, related_name='blogs', to='tags.Tag', verbose_name='\u041a\u0430\u0442\u0435\u0433\u043e\u0440\u0438\u0438'),
        ),
    ]
