# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-22 09:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20180422_0853'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_archive',
            field=models.BooleanField(default=False, verbose_name='\u041f\u043e\u0441\u0442 \u0432 \u0430\u0440\u0445\u0438\u0432\u0435'),
        ),
        migrations.AlterField(
            model_name='post',
            name='category_post',
            field=models.ManyToManyField(blank=True, related_name='posts', to='tags.Tag', verbose_name='\u041a\u0430\u0442\u0435\u0433\u043e\u0440\u0438\u0438'),
        ),
    ]
