# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-11 15:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('comments', '0001_initial'),
        ('posts', '0001_initial'),
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='post_comment',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='posts.Post', verbose_name='\u041f\u043e\u0441\u0442 \u043a \u043a\u043e\u043c\u043c\u0435\u043d\u0442\u0443'),
        ),
        migrations.AddField(
            model_name='comment',
            name='question_comment',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='comments_quest', to='questions.Question', verbose_name='\u0412\u043e\u043f\u0440\u043e\u0441 \u043a \u043a\u043e\u043c\u043c\u0435\u043d\u0442\u0443'),
        ),
    ]
